version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker-compose" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

