---
# This file is used for a local dev env, not a part of this container pod.
services:
  postgresql:
    image: docker.io/bitnami/postgresql:16.1.0
    container_name: "postgresql"
    ports:
      - "5435:5432"
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_POSTGRES_PASSWORD=password
      - POSTGRESQL_DATABASE=scheduler
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_MAX_CONNECTIONS=1000
