spring:
  application:
    name: "scheduler"
  datasource:
    url: ${dbUrl}
    username: ${dbUser}
    password: ${dbPassword}
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  hikari:
    poolName: "scheduler-pool"
    maximumPoolSize: 10
    minimumIdle: 2
    idleTimeout: 30s
    connectionTimeout: 2m
    maxLifetime: 30m

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all endpoints
  server:
    port: 8081

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true

server:
  port: 8080

scheduler:
  threadCount: 5
  pollingDuration: 10s
  lowerLimitFractionOfThreads: 0.5
  upperLimitFractionOfThreads: 1.0
  httpTaskName: http-task
