---
build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: true
  checkExhaustiveness: false
  excludes: ''

comments:
  active: true
  DeprecatedBlockTag:
    active: true
  OutdatedDocumentation:
    active: true
    matchTypeParameters: true
    matchDeclarationsOrder: true
    allowParamOnConstructorProperties: false
  UndocumentedPublicClass:
    active: true
    excludes: [ '**/test/**', '**/testFixtures/**' ]
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: false
    searchInInnerInterface: true
    searchInProtectedClass: false
  UndocumentedPublicFunction:
    active: true
    excludes: [ '**/test/**', '**/testFixtures/**' ]
    searchProtectedFunction: true
  UndocumentedPublicProperty:
    active: false
    excludes: [ '**/test/**', '**/testFixtures/**' ]
    searchProtectedProperty: true

complexity:
  active: true
  ComplexInterface: # Single Responsibility Principle
    active: true
    threshold: 7
    includeStaticDeclarations: false
    includePrivateDeclarations: false
    ignoreOverloaded: false
  LabeledExpression:
    active: true
    ignoredLabels: [ ]
  LongParameterList:
    active: true
    functionThreshold: 20
    constructorThreshold: 20
    ignoreDefaultParameters: false
    ignoreDataClasses: true
    ignoreAnnotatedParameter: [ ]
  NamedArguments:
    active: true
    threshold: 3
    ignoreArgumentsMatchingNames: false
  NestedBlockDepth:
    active: true
    threshold: 3
  NestedScopeFunctions:
    active: false
    threshold: 1
    functions:
      - 'kotlin.apply'
      - 'kotlin.run'
      - 'kotlin.with'
      - 'kotlin.let'
      - 'kotlin.also'
  ReplaceSafeCallChainWithRun:
    active: false
  StringLiteralDuplication:
    active: true
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/androidUnitTest/**'
      - '**/androidInstrumentedTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
      - '**/*gradle.kts'
    threshold: 2
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: false
    ignoreStringsRegex: '$^'

coroutines:
  active: true
  SuspendFunSwallowedCancellation:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    active: true
  RedundantSuspendModifier:
    active: false # giving false positives

exceptions:
  active: true
  NotImplementedDeclaration:
    active: true
  ObjectExtendsThrowable:
    active: true

naming:
  active: true
  BooleanPropertyNaming:
    active: true
    allowedPattern: '^(is|has|are|does|can|should|will|did|was)'
  NonBooleanPropertyPrefixedWithIs:
    active: true


potential-bugs:
  active: true
  CastNullableToNonNullableType:
    active: true
  CastToNullableType:
    active: true
  IgnoredReturnValue: # TODO needs type resolution. Would be good for Outcome value
    active: true
    restrictToConfig: false


style:
  active: true
  BracesOnIfStatements:
    active: true
    singleLine: 'never'
    multiLine: 'always'
  BracesOnWhenStatements:
    active: true
    singleLine: 'necessary'
    multiLine: 'always'
  DataClassContainsFunctions:
    active: false
    conversionFunctionPrefix:
      - 'to'
    allowOperators: false
  DataClassShouldBeImmutable:
    active: true
  DestructuringDeclarationWithTooManyEntries:
    active: false
    maxDestructuringEntries: 3
  DoubleNegativeLambda:
    active: true
    negativeFunctions:
      - reason: 'Use `takeIf` instead.'
        value: 'takeUnless'
      - reason: 'Use `all` instead.'
        value: 'none'
    negativeFunctionNameParts:
      - 'not'
      - 'non'
  EqualsNullCall:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ForbiddenAnnotation:
    active: true
    annotations:
      - reason: 'it is a java annotation. Use `Suppress` instead.'
        value: 'java.lang.SuppressWarnings'
      - reason: 'it is a java annotation. Use `kotlin.Deprecated` instead.'
        value: 'java.lang.Deprecated'
      - reason: 'it is a java annotation. Use `kotlin.annotation.MustBeDocumented` instead.'
        value: 'java.lang.annotation.Documented'
      - reason: 'it is a java annotation. Use `kotlin.annotation.Target` instead.'
        value: 'java.lang.annotation.Target'
      - reason: 'it is a java annotation. Use `kotlin.annotation.Retention` instead.'
        value: 'java.lang.annotation.Retention'
      - reason: 'it is a java annotation. Use `kotlin.annotation.Repeatable` instead.'
        value: 'java.lang.annotation.Repeatable'
      - reason: 'Kotlin does not support @Inherited annotation, see https://youtrack.jetbrains.com/issue/KT-22265'
        value: 'java.lang.annotation.Inherited'
  ForbiddenComment:
    active: false
    comments:
      - reason: 'Forbidden FIXME todo marker in comment, please fix the problem.'
        value: 'FIXME:'
      - reason: 'Forbidden TODO todo marker in comment, please do the changes.'
        value: 'TODO:'
    allowedPatterns: ''
  ForbiddenImport:
    active: false
    imports: [ ]
    forbiddenPatterns: ''
  ForbiddenMethodCall:
    active: true
    methods:
      - reason: 'print does not allow you to configure the output stream. Use a logger instead.'
        value: 'kotlin.io.print'
      - reason: 'println does not allow you to configure the output stream. Use a logger instead.'
        value: 'kotlin.io.println'
      - reason: 'Instant.now() is not recommended as its hard to mock things. Use a clock.instant() instead.'
        value: 'java.time.Instant.now'
  ForbiddenSuppress:
    active: false
    rules: [ ]
  MagicNumber:
    active: true
    excludes: [ '**/test/**', '**/testFixtures/**', '**/*.kts' ]
    ignoreNumbers: [ '0', '1' ]
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreRanges: false
    ignoreExtensionFunctions: true
  MandatoryBracesLoops:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 100
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
    excludeRawStrings: true
  MultilineLambdaItParameter:
    active: true
  NoTabs:
    active: true
  NullableBooleanCheck:
    active: true
  OptionalUnit:
    active: true
    excludes: [ '**/test/**', '**/testFixtures/**' ]
  ReturnCount: # Early returns are great for readability!
    active: false
  StringShouldBeRawString:
    active: true
    maxEscapedCharacterCount: 2
    ignoredCharacters: [ ]
  TrailingWhitespace:
    active: true
  TrimMultilineRawString:
    active: true
    trimmingMethods:
      - 'trimIndent'
      - 'trimMargin'
  UnderscoresInNumericLiterals:
    active: true
    acceptableLength: 4
    allowNonStandardGrouping: false
  UseDataClass:
    active: true
    allowVars: false
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  WildcardImport:
    active: true